UPDATE app_state SET data=json_set(data,'$.feedbackMessages',json((
SELECT json_group_array(json(CASE
WHEN json_extract(value,'$.id')='702cf5ef-14a3-4e0e-8950-c14b1cdd455d' THEN json_patch(value,json_object('status','done','adminComment','Corrigido na versão 142: ao recarregar, aparece a verificação de sessão em vez de piscar o formulário de login. Falhas de conexão oferecem tentar novamente sem apagar a sessão salva.','updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'completedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')))
WHEN json_extract(value,'$.id')='c6482c92-518a-44e1-b44d-fee5bcbb1928' THEN json_patch(value,json_object('status','done','adminComment','Versão 142: painel lateral de saldo e históricos acompanha a rolagem no computador, com altura limitada e rolagem interna. Em telas menores permanece no fluxo para não cobrir controles. Voo com contador animado, atualização compacta e opção de resgate automático no servidor.','updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'completedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')))
WHEN json_extract(value,'$.id')='563c6329-e2f5-469d-b255-d4ac7d5fd0d1' THEN json_patch(value,json_object('status','done','adminComment','Versão 142: os itens antigos da loja agora se chamam Emblemas do Perfil. Insígnias são as conquistas montadas no Álbum de cartas. IDs, compras e equipamentos existentes preservados.','updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'completedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')))
WHEN json_extract(value,'$.id')='67f5e8a1-29e0-43f5-9089-35ec957b27db' THEN json_patch(value,json_object('status','done','adminComment','Versão 142: cinco coleções, 25 cartas e cinco insígnias. Chance de 40% na primeira atividade válida de cada tipo (água 500 ml, meme, frase, comentário em publicação alheia e voto), até duas cartas por dia. Trocas de repetidas com aceite e revalidação. Pacote de três cartas na loja, aberto no Perfil com animação: 90% básica e 10% rara por carta. Montagem consome uma de cada; moedas preservadas.','updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'completedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')))
WHEN json_extract(value,'$.id')='bb6d5f8e-254c-40a9-8cb2-72414f077c99' THEN json_patch(value,json_object('status','pending','adminComment','Excesso de CPU confirmado anteriormente no Cloudflare. Versão 142 reduz serialização do banco e substitui respostas completas do voo por respostas compactas; consulta do voo passa de 250 para 750 ms, com animação local. Resgate automático é apurado no servidor mesmo após atraso. Mantido pendente para validar ausência de reincidência em uso real; não há garantia de eliminar toda falha de rede ou limite do plano.','updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')))
WHEN json_extract(value,'$.id')='d16e84f9-b354-49ec-95be-1b35501148cb' THEN json_patch(value,json_object('status','pending','adminComment','Versão 142 mantém as otimizações anteriores de estado e acrescenta gravação JSON compacta, status compacto do voo e verificação de sessão sem piscar login. Falha de rede permite tentar novamente sem sair da conta. Ocorrências gerais de lentidão/CPU continuam em acompanhamento após a publicação; o resgate manual ainda depende da conexão.','updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')))
ELSE value END)) FROM json_each(app_state.data,'$.feedbackMessages')
)),'$.settings.release142FeedbackAt',strftime('%Y-%m-%dT%H:%M:%fZ','now')),revision=revision+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id=1 AND json_extract(data,'$.settings.release142FeedbackAt') IS NULL;
