WITH updates(id,status,comment) AS (VALUES
 ('2c71e0ef-52c2-4cba-91e9-96da2b9080e2','done','Publicado na versão 135: Insígnia Cometa (220), Nome Rubi Estelar (240), Moldura Órbita Prateada (310), Antídoto de Maldição (260) e Acordo Estelar (120). Antídoto remove maldição comprada em você, nunca sorteio ou dívida. Acordo prorroga contrato novo por 24h, uma vez. Testes de regras e consumo passaram; nenhuma moeda distribuída.'),
 ('7c877940-3a7e-4580-82ab-ab66fe3d3643','done','Publicado: novos empréstimos vencem em 48h, com juros fixos de 20%. Atraso ativa tema Bandido Estelar, aviso e acompanhamento visual lento do cursor, preservando o ponto real de clique e o cursor obrigatório do sorteado. Impede entrada em novas rodadas; nunca remove alguém de rodada iniciada. Resgate promocional após atingir a meta paga primeiro a dívida. Quitação restaura visuais. Contratos antigos mantêm regras anteriores. Pagamentos, prazo e participação testados.'),
 ('7400b5b7-aa8a-4133-96ed-f0be93a56a0b','done','Publicado: após duas perdas consecutivas na roleta, o ET oferece acesso às condições no perfil. Aparece só após a animação, uma vez por sessão/usuário, e não aparece com dívida ativa. Pode fechar ou ignorar. Nenhum empréstimo é contratado automaticamente; juros e penalidades são informados antes da confirmação.'),
 ('d16e84f9-b354-49ec-95be-1b35501148cb','pending','Causa confirmada no painel: Worker exceeded CPU time limit. Exemplo de 02/09 às 13:32 BRT: GET /api/state, 503, 37ms CPU, 335ms wall time, versão 133. Versão 135 reaproveita cálculos de títulos, extrato e temporada na resposta e limita cache de conversão de datas a 2048 entradas. Testes passaram. Mantido aberto até validar comportamento real após a publicação; não significa erro de senha ou esgotamento das 100 mil requisições.'),
 ('bb6d5f8e-254c-40a9-8cb2-72414f077c99','pending','Observabilidade consultada diretamente, filtro de erros das últimas 24h. Registros confirmam excesso de CPU em /api/state e ocorrências anteriores em /api/events, /api/casino/play, /api/profile/avatar e /api/casino/flight/status. O encerramento por CPU não trouxe linha de stack específica. Otimizações da resposta comum e de datas publicadas na 135; é necessário acompanhar novas ocorrências, sem atribuir falhas ao D1 ou KV sem evidência.')
)
UPDATE app_state SET data=json_set(data,'$.feedbackMessages',json((
 SELECT json_group_array(json(CASE WHEN u.id IS NULL THEN f.value ELSE json_patch(f.value,json_object('status',u.status,'adminComment',u.comment,'updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'completedAt',CASE WHEN u.status='done' THEN strftime('%Y-%m-%dT%H:%M:%fZ','now') ELSE NULL END)) END))
 FROM json_each(app_state.data,'$.feedbackMessages') f LEFT JOIN updates u ON u.id=json_extract(f.value,'$.id')
))),revision=revision+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=1;
