WITH updates(id,status,comment) AS (VALUES
 ('47385206-76de-4d49-9974-9eeaaea65b66','done','Publicado na versão 134: selecione Marcar pessoa no comentário ou escreva @Nome completo. A pessoa recebe aviso no sino. Marcações repetidas no mesmo comentário não duplicam avisos; edição preserva o horário das marcações mantidas. Limite de cinco pessoas por comentário; contas inativas e automarcações são ignoradas. Testes de validação e permissões passaram.'),
 ('d5e726ce-c387-479a-9a51-d007567e0f4c','done','Publicado na versão 134: apenas o resultado mais recente de cada jogo fica aberto; os outros resultados recentes ficam em Ver mais, com altura limitada. Nenhuma jogada foi apagada e os cálculos permanecem iguais.'),
 ('b0e95727-a372-4b0d-8b4a-c2e42d75be80','done','Publicado na versão 134: removida regra do Galáxia que alterava posição e empilhamento de todos os elementos. Menu e cabeçalho preservados. Corrigida também a prévia Nebulosa e a mistura com o modo claro. Validação local com HTML/CSS reais: 13 modos visuais, seis páginas, larguras de 390 e 1366 px, total de 156 verificações; sem deslocamento do menu/cabeçalho ou rolagem horizontal. Troca entre todos os nove temas e restauração da preferência testadas.'),
 ('d6e4ad90-1251-4060-badd-41e7f6be8ef8','done','Publicado na versão 134: rótulos e valores do painel dos jogos têm espaçamento e alinhamento responsivos. Jogadas hoje não fica mais grudado ao número.'),
 ('d16e84f9-b354-49ec-95be-1b35501148cb','pending','Em acompanhamento. Consulta oficial em 02/09: um erro exceededResources na faixa das 16h UTC; nenhum erro de execução nas faixas das 17h e 18h UTC até a consulta. Otimizações anteriores de cache e conexões permanecem ativas. Isso não comprova eliminação de todas as demoras no login; não encerrado.'),
 ('bb6d5f8e-254c-40a9-8cb2-72414f077c99','pending','Métricas oficiais consultadas em 02/09: um exceededResources na faixa das 16h UTC, nenhum erro de execução nas faixas das 17h e 18h UTC até a consulta. O agregado não identifica a rota nem diferencia CPU e memória. Mantido em investigação, sem afirmar que todos os timeouts foram eliminados.'),
 ('2c71e0ef-52c2-4cba-91e9-96da2b9080e2','pending','Sugestão lida. Novos visuais e poderes ficam separados deste lote de correções; ainda não implementados.'),
 ('7c877940-3a7e-4580-82ab-ab66fe3d3643','pending','Sugestão lida. Prazo de dois dias, consequências de atraso, exclusão do sorteio e abatimento do bônus ainda não foram implementados. Contratos, saldos e participação atuais foram preservados neste lote.'),
 ('7400b5b7-aa8a-4133-96ed-f0be93a56a0b','pending','Sugestão lida. Oferta do Agiota ao perder na roleta ainda não foi implementada; nenhuma oferta automática ou empréstimo foi criado neste lote.')
)
UPDATE app_state SET data=json_set(data,'$.feedbackMessages',json((
 SELECT json_group_array(json(CASE WHEN u.id IS NULL THEN f.value ELSE json_patch(f.value,json_object('status',u.status,'adminComment',u.comment,'updatedAt',strftime('%Y-%m-%dT%H:%M:%fZ','now'),'completedAt',CASE WHEN u.status='done' THEN strftime('%Y-%m-%dT%H:%M:%fZ','now') ELSE NULL END)) END))
 FROM json_each(app_state.data,'$.feedbackMessages') f LEFT JOIN updates u ON u.id=json_extract(f.value,'$.id')
))),revision=revision+1,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=1;
