import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const src=await readFile(new URL('../legacy-server.mjs',import.meta.url),'utf8');
class HttpError extends Error { constructor(status,message){super(message);this.status=status;} }
const db={settings:{currentRoundId:null}, users:[{id:'u',active:true,eligible:true}],draws:[],economy:{loans:[],creditAdjustments:[],forcedCursors:[],purchases:[],powerUses:[]}};
let wallet=50, body={amount:100}, response;
const ctx=vm.createContext({db,HttpError,Date,randomUUID:()=>crypto.randomUUID(),walletFor:()=>wallet,addCredits:(_,amount)=>{wallet+=amount;},requireAuth:()=>({user:db.users[0]}),readJson:async()=>body,persist:async()=>{},broadcastRefresh(){},json:(_,status,value)=>{response={status,value};},stateFor:()=>({}),res:{},req:{method:'POST'},route:'/api/loans/borrow'});
vm.runInContext(src.slice(src.indexOf('function activeLoanFor('),src.indexOf('function roundAcceptsNewParticipants(')),ctx);
const handler=vm.runInContext('(async()=>{'+src.slice(src.indexOf("  if (req.method === 'POST' && route === '/api/loans/borrow')"),src.indexOf("  if (req.method === 'POST' && route === '/api/shop/purchase')"))+'})',ctx);
await handler();const loan=db.economy.loans[0];assert.equal(wallet,150);assert.equal(loan.totalDue,120);assert.ok(Math.abs(Date.parse(loan.dueAt)-Date.parse(loan.createdAt)-172800000)<100);
await assert.rejects(handler(),e=>e.status===409);assert.equal(wallet,150);
loan.dueAt=new Date(Date.now()-1000).toISOString();assert.equal(vm.runInContext('eligibleUsers().length',ctx),0);
db.settings.currentRoundId='existing';db.settings.currentParticipantIds=['u'];assert.equal(vm.runInContext('eligibleUsers().length',ctx),1);
assert.equal(vm.runInContext("applyLoanPayment('u',70,'test')",ctx),70);assert.equal(loan.remainingDue,50);assert.equal(wallet,80);
assert.equal(vm.runInContext("applyLoanPayment('u',500,'test')",ctx),50);assert.equal(wallet,30);assert.equal(loan.status,'paid');assert.equal(vm.runInContext("applyLoanPayment('u',500,'test')",ctx),0);
const legacy={id:'old',userId:'u',status:'active',remainingDue:120,createdAt:'2025-01-01',payments:[]};db.economy.loans.push(legacy);assert.equal(vm.runInContext("overdueLoanFor('u')",ctx),null);
legacy.status='paid';loan.status='active';loan.remainingDue=10;loan.extendedAt=null;
ctx.SHOP_CATALOG=[{id:'extension',type:'power',value:'loanExtension',consumable:true},{id:'cleanse',type:'power',value:'cleanseCursor',consumable:true}];
let consumed=0;ctx.consumePower=()=>{consumed++;};ctx.isForcedCursorActive=()=>true;
const powers=vm.runInContext('(async()=>{'+src.slice(src.indexOf("  if (req.method === 'POST' && route === '/api/powers/use')"),src.indexOf("  if (req.method === 'POST' && route === '/api/powers/cancel')"))+'})',ctx);
ctx.route='/api/powers/use';body={itemId:'extension'};await powers();assert.equal(consumed,1);assert.ok(Date.parse(loan.dueAt)>Date.now()+86300000);await assert.rejects(powers(),e=>e.status===409);assert.equal(consumed,1);
body={itemId:'cleanse'};await assert.rejects(powers(),e=>e.status===409);assert.equal(consumed,1);
db.economy.forcedCursors.push({targetUserId:'u',style:'giant-slow'});await powers();assert.equal(consumed,2);assert.equal(db.economy.forcedCursors.length,0);
db.draws.push({type:'gay',winnerId:'u'});db.economy.forcedCursors.push({targetUserId:'u'});await assert.rejects(powers(),e=>e.status===409);assert.equal(consumed,2);
ctx.CASINO_CASHOUT_THRESHOLD=500;
const account={balance:500,cashedOut:false};ctx.casinoAccountFor=()=>account;
ctx.route='/api/casino/cashout';wallet=30;loan.status='active';loan.remainingDue=120;
const cashout=vm.runInContext('(async()=>{'+src.slice(src.indexOf("  if (req.method === 'POST' && route === '/api/casino/cashout')"),src.indexOf("  if (req.method === 'POST' && route === '/api/notifications/read')"))+'})',ctx);
await cashout();assert.equal(wallet,410);assert.equal(response.value.casinoCashout,380);assert.equal(response.value.debtPayment,120);assert.equal(loan.status,'paid');
await assert.rejects(cashout(),e=>e.status===409);assert.equal(wallet,410);
account.cashedOut=false;account.balance=499;await assert.rejects(cashout(),e=>e.status===409);assert.equal(wallet,410);
console.log('PASS: 48h, 20% interest, duplicate prevention, integer partial/full repayment, legacy contracts, frozen rounds, one extension, curses, promotional debit and mandatory winner.');
